src/extension.ts
src/types.ts
tsrelay/main.go

This PR does a couple of things: 
1. Sets the OFFLINE error when key is expired. We can potentially make it a special message. 
2. It also adds a socket path for extension development if we need it to point to a different localapi or server.

Show error message for expired node key

---

.backportrc.json

Versions should be `major.minor`.
Resolves backport Github action failing: https://github.com/tailscale-dev/vscode-tailscale/actions/runs/5203821591

ci: Fix branch label mapping for backport

---

src/extension.ts
src/types.ts
tsrelay/main.go

This will backport the following commits from `main` to `release-branch/v0.4`:
- [Show error message for expired node key (#1)](https://github.com/tailscale-dev/vscode-tailscale/pull/1)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

[release-branch/v0.4] Show error message for expired node key (#1)

---

src/webviews/serve-panel/simple-view.tsx

This will backport the following commits from `main` to `release-branch/v0.4`:
- [SimpleView: only show service message when there is a port (#9)](https://github.com/tailscale-dev/vscode-tailscale/pull/9)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

[release-branch/v0.4] SimpleView: only show service message when there is a port (#9)

---

.github/renovate.json5

Renovate is a popular tool in the JavaScript ecosystem that automates dependency management and helps keep your project's dependencies up to date. It is designed to work with package managers like npm, Yarn, and others.
Renovate will open a PR when a package is updated,  grouping them by the rules defined in this PR.

ci: Add renovate config

---

src/tailscale/cli.ts
src/types.ts
tsrelay/main.go

This PR changes the address url stdout to be in json format and lets tsrelay come up with its own once by default. This way, we can add more details that a client such as vscode might need to extract out of tsrelay at server startup.

Output server details as json

---

tsrelay/main.go

This PR returns an explicit json error with status 403 for when LocalBackend returns an AccessDenied error on SetServe. 
The UI could then catch the error and display the command to the user as a manual resolution

Return manual resolution when access is denied to LocalBackend

---

src/tailscale/cli.ts

Use ./tool/go for development mode instead of go. This allows the development mode to work when the go binary is not in the PATH.
Fixes #66

src/tailscale/cli: fix go path for development mode

---

.vscode/launch.json

When debugging the extension, we can run VS Code with "--disable-extensions" to prevent any extensions on the host from being run.

DX: Disable other extensions in development

---

src/tailscale/cli.ts
src/tailscale/error.ts
src/types.ts
tsrelay/main.go

This PR checks the env vars to see if we're running inside of flatpak, and if saw prepends the pkexec with flatpak-spawn in order rerun tsrelay as sudo. 
We also run `flatpak override` so the user doesn't have to. 
Fixes https://github.com/tailscale-dev/vscode-tailscale/issues/76

Run flatpak-spawn when pkexec is needed

---

profiles/offline.json
profiles/snapshot.mjs
tsrelay/local_client.go
tsrelay/main.go

This PR adds the ability to mock LocalClient responses via `-mockfile` so that we can test vscode <-> tsrelay communication without requiring a live tailscaled server.

Add ability to mock LocalClient

---

README.md
package.json
src/tailscale/cli.ts
tsrelay/portdisco.go

This PR allows users to turn on/off port discovery via the vscode settings. This should unblock users who don't want to see much noise, but we can make further enhancements in follow up PRs such as 'snoozing' or a button in the notification to let them know of this option. 
Fixes https://github.com/tailscale-dev/vscode-tailscale/issues/21
Updates https://github.com/tailscale-dev/vscode-tailscale/issues/80

Make port discovery optional via settings

---

src/ts-file-system-provider.ts

We incorrectly add an empty string item for empty directories like the screenshot below:
This PR skips those lines.

File explorer: remove incorrect item for empty dir

---

package.json
yarn.lock

Prepublish had platform specific logic that prevented Windows from building.

package.json: Use concurrently for run scripts

---

package.json

Moved to be more consistent with the Kubernetes extension. It's a hugely popular extension, so I think it's a good idea to follow their lead.
Open SSH => Terminal
Open remote connection => Attach VS Code
Changed order and put Terminal first, since it's likely to be more common and is less disruptive than attaching VS Code.

package.json: update context menu items

---

src/node-explorer-provider.ts
src/ts-file-system-provider.ts

Note: We shouldn't use the `path` node library for parsing URLs. It's for files and is platform specific. We can assume '/'.
Also we should look at the URI we were putting together in getChildren (node-explorer-provider.ts). From what I can tell we would've always had a double leading forward slash.

Fix Windows bugs in Node explorer view

---

package.json

We will always default to the home directory, which can still be overwritten per host.

Remove defaultRootPath configuration option

---

src/node-explorer-provider.ts
tsrelay/handler/get_serve.go

This PR ensures offlines nodes are not expandable and also sorts them at the bottom of the list.

Ensure offline node is not expandable

---

src/node-explorer-provider.ts

This PR ensures a user is prompted before they delete a remote file or directory:
Clsoes ENG-1935

Prompt user before deleting a file or directory

---

package.json
src/extension.ts
src/node-explorer-provider.ts

This PR ensures that if a user has no peers _and_ it's not an error from the backend, then we prompt them to add their first peer. 
Fixes ENG-1922

Fix empty peer list with link to adding node

---

src/node-explorer-provider.ts
src/types.ts
src/utils/string.ts
tsrelay/handler/get_serve.go

Nodes that are external to a user's Tailnet, or "Shared In" should be identified by having the rest of the DNS name set as a description.
Additionally, we are displaying the name according to the DNS entry, not the OS's hostname.
Closes ENG-1919
Stacked on https://github.com/tailscale-dev/vscode-tailscale/pull/147

Node Explorer: Include full DNSName for external nodes

---

src/extension.ts
src/node-explorer-provider.ts

The name at the top is not always tailnet name, so let's call it dipslayName. 
Also PeerTree doesn't need the entire object, just the name.

Distinguish between display name and tailnet name

---

src/node-explorer-provider.ts

When you hover over a node name, if it's online, it just says the node name. If it's offline, it says "$node-name is offline"
This adds "is online" so that the tooltip is consistent between offline/online states.
Fixes ENG-1959
---------
Signed-off-by: Sam Linville <sam@tailscale.com>

Update node tooltips to standardize "is online" / "is offline"

---

package.json
resources/walkthrough/share-port.md
src/extension.ts
src/node-explorer-provider.ts
src/tailscale/cli.ts

I was finding it difficult to remember the hierarchy of the TreeView, as the naming has not been consistent over time. This attempts to create a naming convention for the TreeItem classes and their contextValue.
I also removed "tailscale-" from the view ID's as they need only be unique within our extension and the larger names made the when clauses more unruly.

Rename view and viewItem contexts for consistency with tree classes

---

package.json
src/node-explorer-provider.ts

Allows for an easy way to retry the file explorer connection.

File Explorer: Add inline context for refresh

---

src/extension.ts
src/filesystem-provider-sftp.ts
src/filesystem-provider-ssh.ts
src/node-explorer-provider.ts
src/ssh-connection-manager.ts
src/types.ts
src/utils/uri.test.ts
src/utils/uri.ts
tsrelay/handler/get_peers.go
tsrelay/handler/get_serve.go

Use full DNSName (or fallback to IPv4) when connecting to different nodes in explorer. 
Fixes ENG-1970

Use Address instead of Hostname to connect

---

src/node-explorer-provider.ts
src/types.ts
tsrelay/handler/get_peers.go

Note that if there's only a single group, render it directly. 
Fixes ENG-1971

Explorer: Separate Node Sections

---

src/node-explorer-provider.ts

When creating a directory using the context from a file, we should use its parent. We can also no longer trigger a rebuild on the provided node.

File Explorer: Fix issue with creating directory from file

---

package.json

This was done so we could do a release during the development.

Node Explorer: Removes setting required to enable

---

package.json
src/node-explorer-provider.ts

Adds context actions for terminal and VS Code Remote to directories. If the action is taken on a directory it will automatically be navigated to.

Node explorer: Enable terminal and VS Code remote navigation

---

package.json
src/extension.ts
src/node-explorer-provider.ts

Using a Tree View Item as a button to trigger a command, which we are doing, is explicitly [called out](https://code.visualstudio.com/api/ux-guidelines/views#tree-views) as a "Don't" in the UX Guidelines.
To adhere to this, we should use an inline context for the external docs link.
On hover, you see the following:
**Tailscale not running:**
**Running but not logged in:**

Node Explorer: Some error message improvements

---

src/filesystem-provider-sftp.ts

When I updated the logic to support recursive deletes for directories, I accidently broke single file deletes.

File Explorer: Fix issue with deleting a file

---

src/sftp.ts

We were writing some of the metadata along with the file. This resolves that.

File Explorer: Use the correct byte offset

---

tsrelay/handler/get_peers.go

Including the root label in the DNSName for display purposes, outside the context of DNS zone files is not ideal.

Node Explorer: Always remove root label from DNSName

---

package.json

This allows extensions to be activated in the context of a "workspace"
which enables the extension to work the web-based VS Code server, ala
code-server.

package.json: support "workspace" extension kind

---

package.json
src/extension.ts
src/filesystem-provider-sftp.ts
src/filesystem-provider-timing.ts
src/filesystem-provider.ts
src/node-explorer-provider.ts
src/sftp.ts
src/ssh.ts

This PR re-enables drag and drop to use the new ssh2 library. SInce we don't show you your local machine in the node explorer, added a downloaded option to get remote files into your workspace
Fixes ENG-1933

Re-enable drag and drop

---

tsrelay/handler/get_peers.go

Put offline peers in a separate group. This improves the UI when there are a lot of peers, and makes it easier to see and reach for the online peers in "All nodes".
Fixes: #185

tsrelay/handler: add offline peer group

---

tsrelay/handler/get_peers.go

The trailing period (root label) was removed from the DNS name in (#181), but should have also been removed from the label which is derived from the DNS name.

Machine Explorer: Exclude DNS root label from address

---

.vscode/tasks.json

VS Code tasks should use tool/yarn, and not the system-wide yarn.

tasks: Use tool/yarn

---

package.json

The extension is no longer just for funnel, so we should update the description to reflect that.

package.json: Updates the description

---

package.json
src/node-explorer-provider.ts

File Explorer: add configuration option to hide dotfiles

---

src/extension.ts
src/node-explorer-provider.ts

Node Explorer: accept subdirectories of ~ for root directory

---

package.json
src/config-manager.ts
src/node-explorer-provider.ts
src/utils/sshconfig.ts
yarn.lock

Node Explorer: prompt to add nodes to SSH config file for VSCode remotes list

---

CHANGELOG.md

```
% git log --pretty=oneline v0.6.2..release-branch/v0.6
(HEAD -> release-branch/v0.6) chore(deps): update dependency @vscode/vsce to ^2.21.0 (#223)
chore(deps): update dependency @types/vscode-webview to ^1.57.2 (#218)
chore(deps): update dependency concurrently to ^8.2.1 (#219)
chore(deps): update dependency lint-staged to ^13.3.0 (#196)
tsrelay: update for 1.50 (#239)
Node Explorer: prompt to add nodes to SSH config file for VSCode remotes list (#233)
Node Explorer: accept subdirectories of ~ for root directory (#230)
File Explorer: add configuration option to hide dotfiles (#221)
package.json: Remove from testing category (#226)
chore(deps): update dependency swr to ^2.2.2 (#195)
chore(deps): update dependency @types/react to ^18.2.21 (#194)
chore(deps): update eslint (#137) …
```

changelog: v0.6.3

---

CHANGELOG.md

I missed the changelog backport for v0.6.3, so re-releasing as v0.6.4

changelog: change release version

---

src/filesystem-provider-sftp.ts
src/filesystem-provider.ts
src/node-explorer-provider.ts
src/sftp.ts

Fixes #209.
The biggest change in this PR is that we'll be treating `vscode.FileType` as a bitfield now, rather than just checking for equality, since the SFTP file provider is modified to return symlinks as `SymbolicLink | File` or `SymbolicLink | Directory` rather than just `SymbolicLink`.
Also, should wait for @shayne (or someone else) to confirm that SFTP to a Windows host still uses `/` as the path separator before merging (unfortunately I don't have a Windows machine to test).

Node Explorer: follow symbolic links to directories

---

src/filesystem-provider-ssh.ts
src/utils/uri.ts

We were escaping spaces while using that value directly in SFTP calls. This caused the escape character (`\`) to be included in the file/directory name. Additionally, if a space was included it would not be able to be deleted as it would issue the delete call to include the escape character.
Closes #231

File Explorer: Fix issue with spaces in filenames
