tailscale-dev/vscode-tailscale

- src/types.ts
- src/webviews/serve-panel/simple-view.tsx
- tsrelay/main.go
Closes #5 
This PR includes a map of a port number to the service (aka the binary/program) that started it.
> Provide information on service underlying a proxy

- .github/workflows/test.yml
- src/extension.ts
It also fixes instances where data was referenced that is no longer returned by the status API.
> ci: Validate types and fix invalid reference

- src/webviews/serve-panel/simple-view.tsx
Do not show an error message when a user has not yet typed in a port.
> SimpleView: only show service message when there is a port

- .github/workflows/test.yml
- src/extension.ts
This will backport the following commits from `main` to `release-branch/v0.4`:
- [ci: Validate types and fix invalid reference (#7)](https://github.com/tailscale-dev/vscode-tailscale/pull/7)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
> [release-branch/v0.4] ci: Validate types and fix invalid reference (#7)

- src/types.ts
- src/webviews/serve-panel/simple-view.tsx
- tsrelay/main.go
This will backport the following commits from `main` to `release-branch/v0.4`:
- [Merge pull request #2 from tailscale-dev/marwan/services](https://github.com/tailscale-dev/vscode-tailscale/pull/2)
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
> [release-branch/v0.4] Merge pull request #2 from tailscale-dev/marwan/services

- README.md
- src/webviews/serve-panel/simple-view.tsx
> serve/simple: Notice for Linux users

- package.json
https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds
> extension: Only run in the UI, not on a remote

- src/tailscale/cli.ts
We run tsrelay in sudo and non-sudo, this PR abstracts the common args passed to both class methods.
> Tiny refactor for common tsrelay args

- package.json
- yarn.lock
@shayne verified this is the minimum version supported. 
Related to https://github.com/tailscale-dev/vscode-tailscale/issues/75
> package.json: change "engines"."vscode" to "^1.74.0"

- .github/renovate.json5
Updates dependencies on Mondays
> renovate: Set schedule

- package.json
- src/extension.ts
- src/node-explorer-provider.ts
- src/ts-file-system-provider.ts
Adds various commands to the node:
> File Explorer: Adds SSH, Remote Window, and Machine Details Commands

- package.json
> Node Explorer: Add inline actions

- src/node-explorer-provider.ts
- src/tailscale/cli.ts
- src/types.ts
- tsrelay/handler/create_serve.go
- tsrelay/handler/get_configs.go
- tsrelay/handler/get_serve.go
FYI: the commit hook asked me to remove the `dipose` method, I'm not sure if it's right or this causes a bug somewhere.
> Use /serve for node explorer for better error handling

- src/extension.ts
- src/node-explorer-provider.ts
- src/ts-file-system-provider.ts
- src/utils/ssh.ts
Note that if the path starts with the home directory, it will be collapsed to `~`
> Fix 'change root directory' TODO + show path in file explorer

- src/node-explorer-provider.ts
- src/types.ts
> Node Explorer: Set note tooltip

- package.json
- src/extension.ts
- src/node-explorer-provider.ts
- src/types.ts
- tsrelay/handler/get_serve.go
> Node Explorer: Include Tailnet name in title

- package.json
- src/extension.ts
- src/filesystem-provider-sftp.ts
- src/sftp.ts
- src/utils/error.ts
> File Explorer: Provide context menu to create a directory

- package.json
- src/filesystem-provider-sftp.ts
- src/node-explorer-provider.ts
> File Explorer: Add rename

- package.json
- src/node-explorer-provider.ts
> File Explorer: Context to add file

- src/ssh-connection-manager.ts
> Show warning for wrong host user

- src/ssh-connection-manager.ts
> ssh-connection-manager.ts: Fix typo (s/ALCs/ACLs)

- CHANGELOG.md
- CONTRIBUTING.md
Starting to move to a changelog that is more "user friendly". Instead of a list of changes presenting a few sentences on what to expect.
> v0.6.0 changelog

- package.json
- src/extension.ts
- src/utils/url.ts
> Node Explorer: Add documentation link to view/title

- package.json
* Adds an inline context item for refresh
* Adds "change root directory"
* Adds "change SSH username"
> File Explorer: Adds node context to file explorer item

- src/node-explorer-provider.ts
> File Explorer: Allow opening of symlinks

- README.md
For consistency with the rest of the file.
> README.md: Use lowercase "internet"

- package.json
We don't think the extension makes sense in the testing category.
> package.json: Remove from testing category

- package.json
- src/node-explorer-provider.ts
> Node Explorer: poll for peer/tailnet updates

- README.md
> README: provide directions for Open VSX

- src/node-explorer-provider.ts
> Node Explorer: Fix issue with pre-existing config block
